export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"博客主页","icon":"home","type":"home","readingTime":{"minutes":0.27,"words":81},"excerpt":""},["/index.html","/README.md"]],
  ["v-38a99084","/notes/aboout-website.html",{"title":"关于这个网站","icon":"code","type":"article","readingTime":{"minutes":0.36,"words":108},"excerpt":"如你所见，这是个个人放放博客的地方。错漏频出很是正常，如果可以，欢迎不吝赐教。 在左侧的侧边栏是网站的导览。如果你想参与进来，可以通过邮件与我联系，在该页面下留言或者发起新 issue。 感谢您的支持！","date":"2022-09-17T00:00:00.000Z","localizedDate":"2022年9月17日","category":["介绍"],"tag":["自述"],"isOriginal":true},["/notes/aboout-website","/notes/aboout-website.md"]],
  ["v-e8b6c472","/notes/",{"title":"关于网站","icon":"creative","type":"page","readingTime":{"minutes":0.04,"words":11},"excerpt":""},["/notes/index.html","/notes/README.md"]],
  ["v-348002e0","/software-config/clion-for-oier.html",{"title":"给 OIer 的 Clion 配置","icon":"code","type":"article","readingTime":{"minutes":1.13,"words":338},"excerpt":"安装 CLion, 安装 single Execute 插件。初始化代码时不要选择关联，新建完文件后更新 Cmake 项目。这样一个项目里面就可以放很多道题目了。","date":"2022-09-17T00:00:00.000Z","localizedDate":"2022年9月17日","category":["软件配置"],"tag":["cpp","C++","IDE"],"isOriginal":true},["/software-config/clion-for-oier","/software-config/clion-for-oier.md"]],
  ["v-4bdc7400","/software-config/",{"title":"软件配置","icon":"creative","type":"page","readingTime":{"minutes":0.05,"words":16},"excerpt":"","category":["使用指南"]},["/software-config/index.html","/software-config/README.md"]],
  ["v-582fbdfd","/notes/format/chinese.html",{"title":"中文渲染测试","icon":"markdown","type":"page","readingTime":{"minutes":83.65,"words":25096},"excerpt":"And in the naked light I saw ten thousand people, maybe more. People talking without speaking, people hearing without listening. People writing songs that voices never shared, no o","category":["渲染测试"],"tag":["中文","渲染"]},["/notes/format/chinese","/notes/format/chinese.md"]],
  ["v-169f3579","/notes/format/markdown.html",{"title":"Markdown 渲染测试","icon":"markdown","type":"page","readingTime":{"minutes":3.12,"words":936},"excerpt":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你应该创建和编写 Markdown 文件，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","category":["渲染测试"],"tag":["Markdown","渲染"]},["/notes/format/markdown","/notes/format/markdown.md"]],
  ["v-f7eca91e","/notes/format/",{"title":"页面渲染测试","icon":"creative","type":"page","readingTime":{"minutes":0.06,"words":18},"excerpt":"","category":["渲染测试"]},["/notes/format/index.html","/notes/format/README.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-f488839c","/category/%E4%BB%8B%E7%BB%8D/",{"title":"介绍 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/介绍/","/category/%E4%BB%8B%E7%BB%8D/index.html"]],
  ["v-58b74110","/tag/%E8%87%AA%E8%BF%B0/",{"title":"自述 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/自述/","/tag/%E8%87%AA%E8%BF%B0/index.html"]],
  ["v-78b4318e","/category/%E8%BD%AF%E4%BB%B6%E9%85%8D%E7%BD%AE/",{"title":"软件配置 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/软件配置/","/category/%E8%BD%AF%E4%BB%B6%E9%85%8D%E7%BD%AE/index.html"]],
  ["v-b314438c","/tag/cpp/",{"title":"cpp 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/cpp/index.html"]],
  ["v-b3165a4c","/tag/c++/",{"title":"C++ 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/c++/index.html"]],
  ["v-b30f2bda","/tag/ide/",{"title":"IDE 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/ide/index.html"]],
]
